# Generated by Django 5.2.17 on 2026-09-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='code_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='otp',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='otp',
            name='salt',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='otp',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='otp',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='otp',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
