# Generated by Django 5.2.17 on 2026-09-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_code_hash_otp_ip_address_otp_salt_otp_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
