# Generated by Django 5.2.17 on 2026-08-07 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('price_per_unit', models.PositiveIntegerField(help_text='UGX per unit at time of order')),
                ('order_type', models.CharField(choices=[('order', 'Regular order'), ('preorder', 'Pre-order')], default='order', max_length=10)),
                ('status', models.CharField(choices=[('placed', 'Payment pending'), ('accepted', 'Order accepted'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('reserved', 'Reserved (pre-order)'), ('cancelled', 'Cancelled')], default='placed', max_length=20)),
                ('delivery_mode', models.CharField(blank=True, choices=[('Motorcycle', 'Motorcycle'), ('Motor truck', 'Motor truck'), ('Pickup', 'Buyer pickup')], default='', max_length=20)),
                ('deposit_percentage', models.PositiveSmallIntegerField(default=0, help_text='For pre-orders only')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.PROTECT, related_name='buyer_orders', to=settings.AUTH_USER_MODEL)),
                ('harvest_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='listings.preharvestplan')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='listings.listing')),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.PROTECT, related_name='seller_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tg_orders',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(help_text='1–5 stars')),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tg_ratings',
                'ordering': ['-created_at'],
            },
        ),
    ]
