# Generated by Django 5.2.17 on 2026-10-05 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_tg_listings_is_acti_e56fc9_idx_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller', 'status'], name='tg_orders_seller__41b342_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status'], name='tg_orders_buyer_i_77741e_idx'),
        ),
    ]
