# Generated by Django 5.2.17 on 2026-08-07 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=7.0, help_text='Platform commission percentage (5–8%)', max_digits=4)),
                ('default_deposit_percentage', models.PositiveSmallIntegerField(default=30, help_text='Default pre-order deposit percentage (10–50%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'tg_platform_settings',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('Airtel', 'Airtel Money')], max_length=10)),
                ('phone', models.CharField(help_text='Phone number used for payment', max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='Amount in UGX')),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('held', 'Held in escrow'), ('released', 'Released to seller'), ('refunded', 'Refunded to buyer'), ('failed', 'Payment failed')], default='pending', max_length=10)),
                ('external_ref', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'db_table': 'tg_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.PositiveIntegerField(help_text='Total order value in UGX')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='e.g. 7.00', max_digits=4)),
                ('commission_amount', models.PositiveIntegerField()),
                ('net_amount', models.PositiveIntegerField(help_text='Amount sent to seller')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to seller'), ('failed', 'Payout failed')], default='pending', max_length=10)),
                ('payout_phone', models.CharField(max_length=20)),
                ('external_ref', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tg_payouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
