# Generated by Django 5.2.17 on 2026-08-07 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Cereals', 'Cereals'), ('Legumes', 'Legumes'), ('Tubers', 'Tubers')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('bunch', 'Bunch'), ('bag', 'Bag'), ('head', 'Head'), ('tray', 'Tray')], max_length=10)),
                ('price', models.PositiveIntegerField(help_text='Price per unit in UGX')),
                ('description', models.TextField(blank=True, default='')),
                ('voice_duration', models.PositiveIntegerField(default=0, help_text='Voice note duration in seconds')),
                ('voice_file', models.FileField(blank=True, upload_to='listings/voice/')),
                ('district', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tg_listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/photos/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'db_table': 'tg_listing_photos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PreHarvestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Cereals', 'Cereals'), ('Legumes', 'Legumes'), ('Tubers', 'Tubers')], max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('date_planted', models.DateField()),
                ('expected_harvest', models.DateField()),
                ('quantity', models.PositiveIntegerField(help_text='Expected total yield')),
                ('reserved', models.PositiveIntegerField(default=0, help_text='Quantity reserved by buyers')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('bunch', 'Bunch'), ('bag', 'Bag'), ('head', 'Head'), ('tray', 'Tray')], max_length=10)),
                ('price', models.PositiveIntegerField(help_text='Price per unit in UGX')),
                ('deposit_percentage', models.PositiveSmallIntegerField(default=30, help_text='Deposit required to reserve (%)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tg_harvest_plans',
                'ordering': ['expected_harvest'],
            },
        ),
    ]
