# Generated by Django 5.2.17 on 2026-10-05 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_active', 'category', 'district'], name='tg_listings_is_acti_e56fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller', 'is_active'], name='tg_listings_seller__38f28f_idx'),
        ),
    ]
