# Generated by Django 5.2.17 on 2026-08-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('examples', models.TextField(blank=True, help_text="Example produce, e.g. 'Tomatoes, mangoes, avocados'")),
                ('color_tint', models.CharField(default='#DDE6D2', help_text='Hex colour for listing card backgrounds', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'tg_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReferencePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField(help_text='Current reference price in UGX')),
                ('week_change', models.IntegerField(default=0, help_text='Percentage change from previous week (e.g. 6 = up 6%, -3 = down 3%)')),
                ('source', models.CharField(default='InfoTrade Connect', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tg_reference_prices',
                'ordering': ['name'],
            },
        ),
    ]
